config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#top'
  get 'home/about' => 'books#about'
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path (current_user) 
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:log_in, keys: [:name])
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show

  end

  def edit
  	
  end

  def destroy
  	
  end

  def update
  	
  end

  def top
    
  end

  def new
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def top
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		@books = @user.books
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
        @user.update(user_params)
        redirect_to user_path(@user.id)
	end

	private 
    def user_params
        params.require(:user).permit(:name, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2">
        <div class="masonry-wrapper-cols">
          <h1>User info</h1>
          <table>
            <tr>
              <th>name</th>
              <th>introduction</th>
            </tr>
            <% users.each do |user| %>
            <tr>
            </tr>
          <%= paginate users %>
          </table>
          
        </div>
      </div>
    </div>
  </div>
</section>

app/views/books/about.html.erb
<h1>Welcome to 
 <strong>Bookers!</strong>
</h1>

app/views/books/index.html.erb
<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
<h1>Books</h1>
<table>
	
	<tr>
		<th>Title</th>
		<th>Opinion</th>
	</tr>
</table>

app/views/books/show.html.erb
<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>

app/views/books/top.html.erb
<h1>welcome to 
    <strong>Bookers</strong>
    !!
</h1>
　<p>In
     <strong>Bookers</strong>,
     you can share and exchange your opinions , inpressions , and emotions
 </p>
  <p>about various books!</p>
  <%= link_to "Log in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers27</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Bookers</a>
    </div>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li><a href="#">Home</a></li>
        <li><a href="#">User</a></li>
        <li><a href="#">Books</a></li> 
        <li><%= link_to "log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li class="active"><a href="#">Home</a></li>
        <li class=''><%= link_to "About", home_about_path %>
        </li>
        <li class=''><%= link_to "sign up", new_user_registration_path %>
        </li> 
        <li class=''> <%= link_to "log in", new_user_session_path %>
        </li>
        
      <% end %>
    </ul>
      </div>
    </nav>
  
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">      
          <section class="slice slice-lg sct-color-1">
            <div class="container">
              <div class="row">
                <div class="col-md-4 col-md-offset-4">
                  <div class="form-user style-1 rounded has-shadow-1"> 
                    <div class="form-header text-center">
                      <h2 class="form-header-title">プロフィール編集</h2>
                    </div>
                    <div class="form-body">
                      <%= form_for(@user) do |f| %>
                         <div class="form-group has-icon">
                           <label class="control-label sr-only" for="inputEmail">Name</label>
                           <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
                           <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                         </div>
                         <div class="form-group has-icon">
                           <div class="user-edit-image">
                             <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                           </div>
                           <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
                           <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
                         </div>                      
                        <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                      <% end %>
                    </div>
                  </div> 
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %></h3>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "pull-right" %></p>
  <% end %>
</div>

<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2">
        <div class="masonry-wrapper-cols">
         <h1>Books</h1>
         <table>

          <tr>
            <th>Title</th>
            <th>Opinion</th>
          </tr>

          <% @books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <td><%= book.opinion %></td>

          </tr>
            
          <% end %>
          </table> 
        </div>
      </div>
    </div>
  </div>
</section>